
Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.provision :shell, path: "provision_file.sh"
  config.vm.network :forwarded_port, guest: 80, host: 4567
  VAGRANT_DEFAULT_PROVIDER = "virtualbox"
  
end
