
Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.provision :shell, path: "provision_file.sh"
  #config.vm.network :forwarded_port, guest: 80, host: 4567
  VAGRANT_DEFAULT_PROVIDER = "virtualbox"
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname="vm1"
    vm1.vm.network "private_network",ip:"192.168.2.101"
  end
  
  config.vm.define "vm2" do |vm2|
  vm2.vm.hostname="vm2"
  vm2.vm.network "private_network",ip:"192.168.2.102"
  end
  
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname="vm3"
    vm3.vm.network "private_network",ip:"192.168.2.103"
  end

end


