
Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  VAGRANT_DEFAULT_PROVIDER = "virtualbox"
  
  config.vm.define "server" do |server|
    vm1.vm.hostname="vm1"
    vm1.vm.network "private_network",ip:"192.168.2.102"
    vm1.vm.provision :shell, path: "server_provision.sh"
  end
  
  config.vm.define "vm1" do |vm1|
  	vm1.vm.hostname="vm1"
  	vm1.vm.network "private_network",ip:"192.168.2.103"
	vm1.vm.provision :shell, path: "provision.sh"
  end
  
  config.vm.define "vm2" do |vm2|
        vm2.vm.hostname="vm2"
        vm2.vm.network "private_network",ip:"192.168.2.104"
	vm2.vm.provision :shell, path: "provision.sh"
  end

end


